PERSO ENV 1/src/objects/Discount__c.object
<CustomObject>
    <fields>
        <fullName>DiscountType__c</fullName>
        <label>DiscountType</label>
        <picklist>
            <picklistValues>
                <fullName>EmployeInterneRenault</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prestataire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandataire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount_Pct__c</fullName>
        <label>Discount_Pct</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PERSO ENV 1/src/objects/HistoryVehicle__c.object
<CustomObject>
    <fields>
        <fullName>ModificationDate__c</fullName>
        <label>ModificationDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewLicencePlate__c</fullName>
        <label>NewLicencePlate</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NewOwner</label>
        <referenceTo>Owner__c</referenceTo>
        <relationshipName>HistoryLicencePlates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewStatus__c</fullName>
        <label>NewStatus</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OldLicencePlate__c</fullName>
        <label>OldLicencePlate</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OldOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OldOwner</label>
        <referenceTo>Owner__c</referenceTo>
        <relationshipName>HistoryLicencePlates1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OldStatus__c</fullName>
        <label>OldStatus</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>HistoryVehicles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HistoryVehicle</label>
    <nameField>
        <label>HistoryVehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HistoryVehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PERSO ENV 1/src/objects/Owner__c.object
<CustomObject>
    <fields>
        <fullName>OwnerStatus__c</fullName>
        <label>OwnerStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EmployeInterneRenault</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prestataire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandataire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Owner</label>
    <nameField>
        <label>Owner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PERSO ENV 1/src/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount_Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Pct__c</fullName>
        <label>Discount_Pct</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>First_Maintenance_Date__c</fullName>
        <label>First Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Registration_Date__c</fullName>
        <label>First Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Immatriculation__c</fullName>
        <label>Immatriculation</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <label>Owner</label>
        <referenceTo>Owner__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_HT__c</fullName>
        <label>Price HT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_TTC__c</fullName>
        <label>Price TTC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entretien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panne</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PERSO ENV 1/src/classes/AP10_Vehicle.cls
public with sharing class AP10_Vehicle {
	
	//create computed information for a vehicle
	public static void createVehicleInformation (List<Vehicle__c> iVeh) {
		createMaintenanceDate(iVeh);
	}
	
	//compute the first maintenance date
	private static void createMaintenanceDate (List<Vehicle__c> iVeh) {
		for (Integer i = 0; i < iVeh.size(); ++i) {
			if (iVeh[i].First_Registration_Date__c != null) {
				//First_Maintenance_Date__c += 6 mois
				Date lDate = iVeh[i].First_Registration_Date__c;
				iVeh[i].First_Maintenance_Date__c = lDate.addMonths(6);
			}
		}
	}
	
	/**** USELESS CODE 
	//Le prix HT a été modifié => on modifie le prix
	public static void updatePrices(List<Vehicle__c> iNewVeh, List<Vehicle__c> iOldVeh) {
		List<Vehicle__c> lUpVehicles = new List<Vehicle__c>();
		for (Integer i = 0; i < iNewVeh.size(); ++i) {
			if (iNewVeh[i].Price_HT__c != null && iNewVeh[i].Price_HT__c != iOldVeh[i].Price_HT__c) {
				lUpVehicles.add(iNewVeh[i]);
			}
		}
		computePrices(lUpVehicles);
		update lUpVehicles;
	}
	*/
	
	//compute the prices
	public static void computePrices(List<Vehicle__c> iNewVeh) {
		Map<Id, Integer> lMap = new Map<Id, Integer>();
		for (Integer i = 0; i < iNewVeh.size(); ++i) {
			if (iNewVeh[i].Price_HT__c != null) {
				//on ajout l'Id de l'owner et l'indice du vehicule dans la liste
				lMap.put(iNewVeh[i].Owner__c, i);
			}
		}
		//recuperation des remises
		//TODO : on peut avoir un Singleton 	=> http://www.tgerm.com/2010/03/apex-implementing-singleton-design.html!!!
		//TODO : si beaucoup de remises : peut poser problèmes. Pour le moment 3 prévu seulement
		//       inutile de chercher une complexite superieure avec une jointure
		List<Discount__c> lDiscounts = [SELECT Id, Discount_Pct__c, DiscountType__c FROM Discount__c];
		//Nota : Percent is a Double
		Map<String, Double> lDiscountsMap = new Map<String, Double>();
		for (Integer i = 0; i < lDiscounts.size(); ++i) {
			if (lDiscounts[i].DiscountType__c != null && lDiscounts[i].Discount_Pct__c != null) {
				lDiscountsMap.put(lDiscounts[i].DiscountType__c, lDiscounts[i].Discount_Pct__c);
			}
		}
		
		//recuperation du type de Owner
		List<Owner__c> lOwners = [SELECT Id, OwnerStatus__c FROM Owner__c WHERE Id IN :lMap.keySet()];
		for (Integer i = 0; i < lOwners.size(); ++i) {
			if (lMap.containsKey(lOwners[i].Id)) {
				if (lDiscountsMap.containsKey(lOwners[i].OwnerStatus__c)) {
					Integer lIdxVeh = lMap.get(lOwners[i].Id);
					//calcul de la remise
					Double lDisc = lDiscountsMap.get(lOwners[i].OwnerStatus__c);
					iNewVeh[lIdxVeh].Discount_Pct__c = lDisc;
					iNewVeh[lIdxVeh].Discount_Amount__c = iNewVeh[lIdxVeh].Price_HT__c * lDisc / 100; 					
					//calcul du prix TTC
					iNewVeh[lIdxVeh].Price_TTC__c = (iNewVeh[lIdxVeh].Price_HT__c - iNewVeh[lIdxVeh].Discount_Amount__c) * 1.196;
				}
			}
		}
	}
	
	//sauvegarde de la plaque d'immatriculation
	public static void updateHistory(List<Vehicle__c> iNewVeh, List<Vehicle__c> iOldVeh) {
		List<Integer> lModifiedLicence = new List<Integer>();
		List<Integer> lModifiedOwner = new List<Integer>();
		List<Integer> lModifiedStatus = new List<Integer>();
		for (Integer i = 0; i < iNewVeh.size(); ++i) {
			if (iNewVeh[i].Immatriculation__c != iOldVeh[i].Immatriculation__c) {
				lModifiedLicence.add(i);
			}
			if (iNewVeh[i].Owner__c != iOldVeh[i].Owner__c) {
				lModifiedOwner.add(i);
			}
			if(iNEwVeh[i].Status__c != iOldVeh[i].Status__c) {
				lModifiedStatus.add(i);
			}
		}
		historyLicencePlate(iNewVeh, iOldVeh, lModifiedLicence);
		historyOwners(iNewVeh, iOldVeh, lModifiedOwner);
		historyStatus(iNewVeh, iOldVeh, lModifiedStatus);
	}
	
	//historisation du changement de plaque
	private static void historyLicencePlate(List<Vehicle__c> iNewVeh, List<Vehicle__c> iOldVeh, List<Integer> iIdx) {
		List<HistoryVehicle__c> lHistList = new List<HistoryVehicle__c>();
		for (Integer i = 0; i < iIdx.size(); ++i) {
			HistoryVehicle__c lObj = new HistoryVehicle__c();
			lObj.Vehicle__c = iNewVeh[iIdx[i]].Id;
			lObj.OldLicencePlate__c = iOldVeh[iIdx[i]].Immatriculation__c;
			lObj.NewLicencePlate__c = iNewVeh[iIdx[i]].Immatriculation__c;
			lObj.ModificationDate__c = Date.today();
			lHistList.add(lObj);
		}
		insert lHistList;
	}
	
	//historisation du changement de propriétaire
	private static void historyOwners(List<Vehicle__c> iNewVeh, List<Vehicle__c> iOldVeh, List<Integer> iIdx) {
		List<HistoryVehicle__c> lHistList = new List<HistoryVehicle__c>();
		for (Integer i = 0; i < iIdx.size(); ++i) {
			HistoryVehicle__c lObj = new HistoryVehicle__c();
			lObj.Vehicle__c = iNewVeh[iIdx[i]].Id;
			lObj.NewOwner__c = iNewVeh[iIdx[i]].Owner__c;
			lObj.OldOwner__c = iOldVeh[iIdx[i]].Owner__c;
			lObj.ModificationDate__c = Date.today();
			lHistList.add(lObj);
		}
		insert lHistList;
	}	
	
	private static void historyStatus(List<Vehicle__c> iNewVeh, List<Vehicle__c> iOldVeh, List<Integer> iIdx) {
		List<HistoryVehicle__c> lHistList = new List<HistoryVehicle__c>();
		for (Integer i = 0; i < iIdx.size(); ++i) {
			HistoryVehicle__c lObj = new HistoryVehicle__c();
			lObj.Vehicle__c = iNewVeh[iIdx[i]].Id;
			lObj.NewStatus__c = iNewVeh[iIdx[i]].Status__c;
			lObj.OldStatus__c = iOldVeh[iIdx[i]].Status__c;
			lObj.ModificationDate__c = Date.today();
			lHistList.add(lObj);
		}
		insert lHistList;
	}
}