PERSO ENV 1/src/objects/Owner__c.object
<CustomObject>
    <fields>
        <fullName>OwnerStatus__c</fullName>
        <label>OwnerStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EmployeInterneRenault</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prestataire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandataire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Owner</label>
    <nameField>
        <label>Owner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PERSO ENV 1/src/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount_Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Pct__c</fullName>
        <label>Discount_Pct</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <label>Owner</label>
        <referenceTo>Owner__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_HT__c</fullName>
        <label>Price HT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_TTC__c</fullName>
        <label>Price TTC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PERSO ENV 1/src/classes/AP11_Owner.cls
public with sharing class AP11_Owner {

	public static void updateOwner(List<Owner__c> iNewOwn, List<Owner__c> iOldOwn) {
		Set<Owner__c> lOwnersSet = new Set<Owner__c>();
		for (Integer i = 0; i < iNewOwn.size(); ++i) {
			if (iNewOwn[i].OwnerStatus__c != null && iNewOwn[i].OwnerStatus__c != iOldOwn[i].OwnerStatus__c) {
				//le statut a change => on doit changer la remise !
				lOwnersSet.add(iNewOwn[i]);
			}
		}
		List<Vehicle__c> lVehicles = [SELECT 
										Id, Price_HT__c, Owner__c, Discount_Pct__c,
										Discount_Amount__c, Price_TTC__c
									 FROM Vehicle__c WHERE Owner__c IN: lOwnersSet];
		AP10_Vehicle.computePrices(lVehicles);
		update lVehicles;
	}
}